### ISSUE TITLE
I'd like to make a mutt theme

### ISSUE THREAD

**Issue by jsatk** [jonathanfilip/lucius#10]
Hi! Lucius is my favorite color scheme.  I always come back to it.  I have it on almost everything use except for mutt.  I was wondering if you were working on a mutt color scheme for Lucius, and if not I was hoping to contribute one to this repo.

**Comment by jonathanfilip** [comment]
I'm not working on anything at the moment, so feel free to make one :).

**Comment by jsatk** [comment]
I'll open a PR if I can get to it. Thank you.
