### ISSUE TITLE
Normal and bright should not be equal

### ISSUE THREAD

**Issue by fedemp** [jonathanfilip/lucius#2]
Hi. I'm considering using this coloscheme for my terminal, but noticed that both normal and bright colors are the same (i.e. 0 and 8, 1 and 9).

AFAIK this could arise some issues if some app relies on the difference between each pair. See  https://github.com/gruntjs/grunt/issues/181 and https://github.com/altercation/solarized/issues/220

**Comment by kcaran** [comment]
In iterm2, I noticed that vim visual highlighting wasn't "working". The ansi7 and ansi8 colors should be silver and grey, not white and black.

The 'LineNr' highlight defines both of those colors, so I modified lucius.py to use it instead of 'Normal'.
